    <script src="${basePath }hplus/js/jquery.min.js?v=2.1.4"></script>
    <script src="${basePath }hplus/js/bootstrap.min.js?v=3.3.5"></script>
    <script src="${basePath }hplus/js/content.min.js?v=1.0.0"></script>
    <script src="${basePath }hplus/js/plugins/flot/jquery.flot.js"></script>
    <script src="${basePath }hplus/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
    <script src="${basePath }hplus/js/plugins/flot/jquery.flot.resize.js"></script>
    <script src="${basePath }hplus/js/plugins/chartJs/Chart.min.js"></script>
    <script src="${basePath }hplus/js/plugins/peity/jquery.peity.min.js"></script>
    <script src="${basePath }hplus/js/demo/peity-demo.min.js"></script>
    <script src="${basePath }hplus/js/plugins/iCheck/icheck.min.js"></script>